openapi: 3.0.0
info:
  title: Courses API
  description: Simple API with QA courses
  version: 1.0.0
servers:
  - url: http://localhost:3000/
paths:
  /courses:
    get:
      summary: Returns a list of courses.
      description: Without any parameters, returns all courses in database
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            maximum: 75 
      responses:
        '200':    # status code
          description: OK
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: object
    post:
      summary: Creates a new course.
      description: Creates a new course and returns an object
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/examples/courses'
              type: object
              properties:
                title:          
                  type: string
                  maximum: 355
                author:    
                  type: string
                  maximum: 50
                isFree:
                  type: boolean
                site:
                  type: string
                  maximum: 355
                type:
                  type: string
                  enum: ["AQA", "QA", "ENG"]
              required:
                - title
                - author
                - type
                - site
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: object

  /courses/{id}:                
    get:
      summary: Returns course by ID.
      description: Returns course by ID
      parameters:
        - name: id
          in: path
          description: Course ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                type: object
                items: 
                  type: object
    put:
      summary: Update course by ID.
      description: Find course by ID and update info, returns updated course info
      parameters:
        - name: id
          in: path
          description: Course ID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/examples/courses'
              type: object
              properties:
                title:          
                  type: string
                  maximum: 355
                author:    
                  type: string
                  maximum: 50
                isFree:
                  type: boolean
                site:
                  type: string
                  maximum: 355
                type:
                  type: string
                  enum: ["AQA", "QA", "ENG"]
              required:
                - title
                - author
                - type
                - site      
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                type: object
                items: 
                  type: object
    delete:
      summary: Delete course by ID.
      description: Delete course by ID and returns message
      parameters:
        - name: id
          in: path
          description: Course ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                type: object
                items: 
                  type: object   
components:
  examples:
    courses:  
      summary: An example of a course
      value:
        title: "Some course"
        author: "John Doe"
        isFree: true
        site: "http://example.com"
        type: "QA"

